### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by panarealty** [bricelam/ImageResizer#21]
Sorry if I missed something but using ImageResizer on Windows 10 for many months now without issue. Today software not working.  Choose files, right click on resize, nothing happens.  Deleted app, re-installed twice (no errors), still does not work.  

Any ideas?
Thank you.
G

**Comment by ferialrunner** [comment]
I also have the same issue. It doesn't show in the context menu on Windows 10. The registry entry for the context menu exists (i checked with CCleaner). Don't really know how to troubleshoot.. 
Any advice will be much appreciated!

**Comment by matteocuccu** [comment]
I had the same problem after i installed the Cumulative Update for Windows 10 Version 1607 for x64-based Systems !
Thanks for any help !

**Comment by bricelam** [comment]
Is this fixed in version [3.1.0-beta1](https://github.com/bricelam/ImageResizer/releases/tag/v3.1.0-beta1)?

**Comment by ferialrunner** [comment]
No. It still doesn't show up in the context menu :( 

Looking at the context menu settings (via CCleaner) shows that it should be there. I attached screenshots. Sorry, I can't help much, as I have no coding or sysadmin experience 

![image](https://cloud.githubusercontent.com/assets/22508010/19222735/1fe5bdc6-8e14-11e6-862c-a8cae704ae78.png)

![image](https://cloud.githubusercontent.com/assets/22508010/19222743/4fb3424e-8e14-11e6-9c63-8d917feab0f7.png)

**Comment by CharlesVidal** [comment]
I haven't seen this issue with ImageResizer specifically, but have for other programs with Windows 10. It has a lot of context menu and taskbar issues. The way I fixed it for a friend was uninstalling the program and re-installing it as an administrator. It's a shot in the dark but just figured I would mention it.

**Comment by panarealty** [comment]
Mine shows up in right click menu but when clicking on it - it does nothing - does not work.

I deleted and re-installed it twice already.

Windows 10.

**Comment by raptyk** [comment]
![nomenuitem](https://cloud.githubusercontent.com/assets/5106486/20643994/6f8931b2-b427-11e6-80ac-cdebef9da453.png)

Same problem here... no menu item on Windows 10 64-bit. I deleted and re-installed it (also in admin mode) - no success.

**Comment by bricelam** [comment]
I'm not able to reproduce these issues, so I can't debug them. If someone can detail the exact steps to reproduce them from a clean Windows install, I'll dig into them. Alternatively, someone experiencing them with enough skill to understand them will have to submit a fix.

**Comment by bricelam** [comment]
FYI, I fixed an issue today in f2cdc25585ad90f617485d404fbf5ec1bd4014ac that would cause **Resize pictures** to not show up in 32-bit operating systems and processes.

**Comment by raptyk** [comment]
Great news, thank you.
